name: Trigger auto deployment for tickethive-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev, main, feature/azure-deployment ]
    paths:
    - '**'
    - '.github/workflows/tickethive-frontend-AutoDeployTrigger-14f4220b-d9e3-46b3-b50e-108a1b46892e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Code Quality (Lint)
        run: npm run lint --if-present

      - name: Run Unit Tests
        run: npm test --if-present

      - name: Build Application
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TICKETHIVEFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TICKETHIVEFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TICKETHIVEFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: tickethiveacr.azurecr.io
          registryUsername: ${{ secrets.TICKETHIVEFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TICKETHIVEFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: tickethive-frontend
          resourceGroup: TicketHive-RG
          imageToBuild: tickethiveacr.azurecr.io/tickethive-frontend:${{ github.sha }}



